// adapters/js.ts
import { buildVarMapping, defaultVarMapper } from './css.js';
export function emitJS(values, manifest) {
    const ids = Object.keys(values).sort();
    let mapping;
    if (manifest)
        mapping = buildVarMapping(ids, manifest);
    const lines = [];
    for (const id of ids) {
        const canonical = mapping ? mapping.get(id).canonical : defaultVarMapper(id);
        if (canonical)
            lines.push(`  "${canonical}": ${JSON.stringify(values[id])}`);
    }
    return `// Generated by DCV. Do not edit.\nexport default {\n${lines.join(',\n')}\n};\n`;
}
